LEAF_DIR="/var/lib/leaf"
DIST_DIR="${LEAF_DIR}/distfiles"
BUILD_DIR="${LEAF_DIR}/build"
PKGBUILD_DIR="${LEAF_DIR}/pkgbuild"
TRACE_DIR="${LEAF_DIR}/trace"
HOOK_DIR="${LEAF_DIR}/hooks"
BINARY_DIR="${LEAF_DIR}/binaries"
TEMP_DIR="${LEAF_DIR}/temp"
INSTALLED_PACKAGES="${LEAF_DIR}/installed"

PARALLEL_JOBS=4
DEFAULT_BUILD_OPTIONS=("strip" "!libtool" "zipman")

COMPRESS_PROG="zstd -19 -T0"
BINARY_EXT=".pkg.tar.zst"

ENABLE_DEBUG_TREE="true"
