#!/bin/bash
set -e

RED_COLOR="\e[1;31m"
YELLOW_COLOR="\e[1;33m"
PURPLE_COLOR="\e[1;35m"
GREEN_COLOR="\e[1;32m"
CLEAR_COLOR="\e[0m"

source /etc/leaf.conf

export LC_ALL=C
export PARALLEL_JOBS
if ! [[ "${PARALLEL_JOBS}" =~ ^[0-9]+$ ]]; then
  export PARALLEL_JOBS="4"
fi
export MAKEFLAGS="-j${PARALLEL_JOBS}"
export NINJAJOBS="${PARALLEL_JOBS}"
export LEAF_DIR="${LEAF_DIR:-/var/lib/leaf}"
export DIST_DIR="${DIST_DIR:-${LEAF_DIR}/distfiles}"
export BUILD_DIR="${BUILD_DIR:-${LEAF_DIR}/build}"
export PKGBUILD_DIR="${PKGBUILD_DIR:-${LEAF_DIR}/pkgbuild}"
export TRACE_DIR="${TRACE_DIR:-${LEAF_DIR}/trace}"
export HOOK_DIR="${HOOK_DIR:-${LEAF_DIR}/hooks}"
export BINARY_DIR="${BINARY_DIR:-${LEAF_DIR}/binaries}"
export TEMP_DIR="${TEMP_DIR:-${LEAF_DIR}/temp}"
export INSTALLED_PACKAGES="${INSTALLED_PACKAGES:-${LEAF_DIR}/installed}"
export DEFAULT_BUILD_OPTIONS=("strip" "!libtool" "zipman")
export COMPRESS_PROG="${COMPRESS_PROG:-zstd -19 -T0}"
export BINARY_EXT="${BINARY_EXT:-.pkg.tar.zst}"
export ENABLE_DEBUG_TREE="${ENABLE_DEBUG_TREE:-true}"

declare -A BUILD_OPTIONS=([strip]="0" [libtool]="0" [zipman]="0")

main() {
  leaf_create_directories
  if [ $# -le 1 ]; then
    case $1 in
      clean)
        leaf_check_permission
        rm -rf {"${BUILD_DIR}","${TEMP_DIR}"}/*
        ;;
      list)
        cat "${INSTALLED_PACKAGES}"
        ;;
      *)
        leaf_print_usage
        ;;
    esac
  else
    local _item
    case $1 in
      prepare|build|install|remove|pack)
        leaf_check_permission
        for _item in "${@:2}"; do
          leaf_find_pkgbuild "${_item}"
          leaf_reset_state
          source "${PKGBUILD_DIR}/${PKG_PREFIX}/${PKG_NAME}".PKGBUILD
          leaf_parse_options
          srcdir="${BUILD_DIR}/${PKG_PREFIX}/${PKG_NAME}"
          pkgdir="${srcdir}"/__pkgdir__
          rm -rf "${srcdir}" && install -dm755 "${srcdir}" && cd "${srcdir}"
          leaf_${1}_package
        done
        ;;
      search)
        leaf_search_package "${@:2}"
        ;;
      show)
        for _item in "${@:2}"; do
          leaf_find_pkgbuild "${_item}"
          leaf_show_package
        done
        ;;
      unpack)
        for _item in "${@:2}"; do
          leaf_check_permission
          leaf_reset_state
          leaf_unpack_package "${_item}"
        done
        ;;
      *)
        leaf_print_usage
        ;;
    esac
    if [ -n "${MESSAGE}" ]; then
      echo -e "${MESSAGE}"
    fi
  fi
}

leaf_error() {
  echo -e "${RED_COLOR}ERROR: $1${CLEAR_COLOR}" && exit 1
}

leaf_warning() {
  echo -e "${YELLOW_COLOR}WARNING: $1${CLEAR_COLOR}"
}

leaf_info() {
  echo -e "${GREEN_COLOR}* $1${CLEAR_COLOR}"
}

leaf_record_message() {
  MESSAGE+="\n${PURPLE_COLOR}* Message from ${PKG_PREFIX}/${PKG_NAME}${CLEAR_COLOR}\n"
  local _item
  for _item in "${@:1}"; do
    MESSAGE+="${GREEN_COLOR}* ${_item}${CLEAR_COLOR}\n"
  done
}

leaf_print_usage() {
  cat << EOF
Usage: leaf [option] [packages]

Options:    
  prepare    prepare packages but do not build
  build      build packages but do not install
  install    install packages
  remove     remove packages
  clean      clean all source folders
  list       list installed packages
  search     search packages by keyword
  show       show package details
  pack       build packages and pack
  unpack     unpack binary packages

                    This leaf does not have Super Cow Powers.
EOF
}

leaf_create_directories() {
  install -dm755 "${DIST_DIR}"
  install -dm755 "${BUILD_DIR}"
  install -dm755 "${PKGBUILD_DIR}"
  install -dm755 "${TRACE_DIR}"
  install -dm755 "${HOOK_DIR}"
  install -dm755 "${BINARY_DIR}"
  install -dm755 "${TEMP_DIR}"
}

leaf_check_permission() {
  [ ${EUID} -eq 0 ] || leaf_error "Permission denied"
}

leaf_find_pkgbuild() {
  local _location="$(find "${PKGBUILD_DIR}" -type f -wholename "*$1*.PKGBUILD" -printf "%P\n")"
  if [ -z "${_location}" ]; then
    leaf_error "Package $1's PKGBUILD does NOT exist"
  elif [[ $(echo "${_location}" | wc -l) == 1 ]]; then
    PKG_PREFIX="$(echo "${_location}" | awk -F'/' '{print $1}')"
    PKG_NAME="$(echo "${_location%.PKGBUILD}" | awk -F'/' '{print $2}')"
  else
    leaf_error "Ambiguous packages, the prefix or version of package must be specified"
  fi
}

leaf_reset_state() {
  options=()
  src_preinstall() {
    :
  }
  src_postinstall() {
    :
  }
  src_preremove() {
    :
  }
  src_postremove() {
    :
  }
}

leaf_parse_options() {
  local _option_array=(${DEFAULT_BUILD_OPTIONS[@]} ${options[@]})
  for option in "${_option_array[@]}"; do
    local key="${option#!}"        # 去掉前缀"!", 得到选项名称
    if [[ "${option}" == !* ]]; then
      BUILD_OPTIONS["${key}"]="0"  # 如果有"!"前缀, 设置为0
    else
      BUILD_OPTIONS["${key}"]="1"  # 否则设置为1
    fi
  done
}

leaf_prepare_package() {
  src_prepare
}

leaf_strip_files() {
  pushd "${pkgdir}" > /dev/null 2>&1
  local _file
  find . -type f | while read -r _file; do
    case $(file -bi "${_file}") in
      *application/x-sharedlib*)             # shared libraries(.so)
        strip --strip-unneeded "${_file}" || leaf_warning "Failed to strip ${_file}"
        ;;
      *application/x-pie-executable*)        # position-independent executables
        strip --strip-unneeded "${_file}" || leaf_warning "Failed to strip ${_file}"
        ;;
      *application/x-archive*)               # static libraries(.a)
        strip --strip-debug "${_file}" || leaf_warning "Failed to strip ${_file}"
        ;;
      *application/x-object*)                # object files(.o)
        case "${_file}" in
          *.ko)                              # kernel module
            strip --strip-unneeded "${_file}" || leaf_warning "Failed to strip ${_file}"
            ;;
          *)
            ;;
        esac
        ;;
      *application/x-executable*)            # executable binaries
        strip --strip-all "${_file}" || leaf_warning "Failed to strip ${_file}"
        ;;
      *)
        ;;
    esac
  done
  popd > /dev/null 2>&1
}

leaf_remove_libtool_files() {
  find "${pkgdir}" -name "*.la" -delete
}

leaf_compress_manpages() {
  pushd "${pkgdir}" > /dev/null 2>&1
  [ ! -d usr/share/man ] || {
    local _item
    find usr/share/man -type f,l | while read -r _item; do
      case $(file -bi "${_item}") in
        *text*)
          /usr/bin/gzip -c -9 "${_item}" > "${_item}".gz
          rm -fv "${_item}"
          ;;
        *symlink*)
          ln -srv "$(readlink -m "${_item}")".gz "$(realpath "${_item}".gz)"
          rm -fv "${_item}"
          ;;
        *)
          ;;
      esac
    done
  }
  popd > /dev/null 2>&1
}

leaf_build_package() {
  leaf_prepare_package
  src_build
  local _option
  for _option in "${!BUILD_OPTIONS[@]}"; do
    case "${_option}" in
      strip)
        [[ "${BUILD_OPTIONS[$_option]}" == "0" ]] || leaf_strip_files
        ;;
      libtool)
        [[ "${BUILD_OPTIONS[$_option]}" == "1" ]] || leaf_remove_libtool_files
        ;;
      zipman)
        [[ "${BUILD_OPTIONS[$_option]}" == "0" ]] || leaf_compress_manpages
        ;;
      *)
        leaf_warning "Unknown build option \`${_option}\`"
        ;;
    esac
  done
  if [[ x"${ENABLE_DEBUG_TREE}" == x"true" ]] && [[ -x "$(echo ${TREE_PROG} | awk '{print $1}')" ]]; then
    ${TREE_PROG} "${pkgdir}"
  fi
}

leaf_trace_package() {
  pushd "$1" > /dev/null 2>&1
  local _trace_dir="${TRACE_DIR}/${PKG_PREFIX}/${PKG_NAME}"
  install -dm755 "${_trace_dir}"
  find . -type d | sort > "${_trace_dir}"/DIRS
  sed -i "1d" "$_trace_dir"/DIRS
  find . -type f | sort > "${_trace_dir}"/FILES
  find . -type l | sort > "${_trace_dir}"/LINKS
  sed -i "s/.//" "${_trace_dir}"/{DIRS,FILES,LINKS}
  popd > /dev/null 2>&1
}

leaf_invoke_hooks() {
  local _hook _target
  local _trace_dir="${TRACE_DIR}/${PKG_PREFIX}/${PKG_NAME}"
  find "${HOOK_DIR}" -type f -name "*.HOOK" | while read -r _hook; do
    source "${_hook}"
    for _target in "${target[@]}"; do
      if [ -n "$(grep -e "${_target}" "${_trace_dir}"/FILES)" ]; then
        operation
        break
      fi
    done
  done
}

leaf_merge_package() {
  pushd $1 > /dev/null 2>&1
  local _trace_dir="${TRACE_DIR}/${PKG_PREFIX}/${PKG_NAME}"
  local _item _mode _owner _group
  cat "${_trace_dir}"/DIRS | while read -r _item; do
    _mode=$(stat -c %a ."${_item}")
    _owner=$(stat -c %u ."${_item}")
    _group=$(stat -c %g ."${_item}")
    install -dm ${_mode} -o ${_owner} -g ${_group} "${_item}"
  done
  cat "${_trace_dir}"/FILES | while read -r _item; do
    _mode=$(stat -c %a ."${_item}")
    _owner=$(stat -c %u ."${_item}")
    _group=$(stat -c %g ."${_item}")
    install -Dm ${_mode} -o ${_owner} -g ${_group} ."${_item}" "${_item}"
  done
  cat "${_trace_dir}"/LINKS | while read -r _item; do
    cp -dp ."${_item}" "${_item}"
  done
  leaf_invoke_hooks
  popd > /dev/null 2>&1
}

leaf_update_package_database() {
  local _item="$(echo "$2" | awk 'BEGIN{FS="/";OFS="\\/"}{print $1,$2}')"
  case $1 in
    add)
      sed -i "/${_item}/d" "${INSTALLED_PACKAGES}"
      echo "$2" >> ${INSTALLED_PACKAGES}
      ;;
    delete)
      sed -i "/${_item}/d" "${INSTALLED_PACKAGES}"
      ;;
  esac
}

leaf_update_environment() {
  ldconfig
  [ ! -r /etc/profile ] || source /etc/profile
}

leaf_install_package() {
  leaf_build_package
  leaf_trace_package "${pkgdir}"
  src_preinstall
  leaf_merge_package "${pkgdir}"
  src_postinstall
  leaf_update_package_database add "${PKG_PREFIX}/${PKG_NAME}"
  leaf_update_environment
  leaf_info "Package ${PKG_PREFIX}/${PKG_NAME} has been installed"
}

leaf_remove_package() {
  [ -n "$(grep "${PKG_PREFIX}/${PKG_NAME}" ${INSTALLED_PACKAGES})" ] || {
    leaf_error "Package ${PKG_PREFIX}/${PKG_NAME} is NOT installed"
  }
  src_preremove
  local _file _link _directory
  cat "${TRACE_DIR}/${PKG_PREFIX}/${PKG_NAME}/FILES" | while read -r _file; do
    rm -fv "${_file}"
  done
  cat "${TRACE_DIR}/${PKG_PREFIX}/${PKG_NAME}/LINKS" | while read -r _link; do
    [ ! -L "${_link}" ] || rm -fv "${_link}"
  done
  cat "${TRACE_DIR}/${PKG_PREFIX}/${PKG_NAME}/DIRS" | while read -r _directory; do
    rmdir --ignore-fail-on-non-empty "${_directory}"
  done
  rm -rf "${TRACE_DIR}/${PKG_PREFIX}/${PKG_NAME}"
  src_postremove
  leaf_update_package_database delete "${PKG_PREFIX}/${PKG_NAME}"
  leaf_update_environment
}

leaf_pack_package() {
  leaf_build_package
  pushd "${srcdir}" > /dev/null 2>&1
  echo "${PKG_PREFIX}" > .PKG_PREFIX
  install -m644 "${PKGBUILD_DIR}/${PKG_PREFIX}/${PKG_NAME}".PKGBUILD .PKGBUILD
  install -dm755 "${BINARY_DIR}"
  local _target="${BINARY_DIR}/${pkgname}-${pkgver}${BINARY_EXT}"
  rm -fv "${_target}"
  tar -I "${COMPRESS_PROG}" -cf "${_target}" "$(basename ${pkgdir})" .PKG{_PREFIX,BUILD}
  popd > /dev/null 2>&1
}

leaf_search_package() {
  local _item _regex
  for _item in "$@"; do
    _regex+="${_item}\|"
  done
  _regex="${_regex:0:${#_regex}-2}"
  find "${PKGBUILD_DIR}" -type f -regex ".*\(${_regex}\).*\.PKGBUILD" -printf "%P\n" | while read -r _item; do
    echo "${_item%.PKGBUILD}"
  done
}

leaf_show_package() {
  source "${PKGBUILD_DIR}/${PKG_PREFIX}/${PKG_NAME}".PKGBUILD
  echo "Package: ${pkgname}"
  echo "Version: ${pkgver}"
  echo "Description: ${pkgdesc}"
  echo "Homepage: ${homepage}"
  echo -e "License: ${license[@]}\n"
}

leaf_unpack_package() {
  srcdir="${TEMP_DIR}/$(basename ${1%.pkg.*})"
  pkgdir="${srcdir}"/__pkgdir__
  rm -rf "${srcdir}" && install -dm755 "${srcdir}" && cd "${srcdir}"
  tar -xf $1 -C "${srcdir}"
  source "${srcdir}"/.PKGBUILD
  PKG_PREFIX="$(cat "${srcdir}"/.PKG_PREFIX)"
  PKG_NAME="${pkgname}-${pkgver}"
  install -Dm644 "${srcdir}"/.PKGBUILD "${PKGBUILD_DIR}/${PKG_PREFIX}/${PKG_NAME}".PKGBUILD
  leaf_trace_package "${pkgdir}"
  src_preinstall
  leaf_merge_package "${pkgdir}"
  src_postinstall
  leaf_update_package_database add "${PKG_PREFIX}/${PKG_NAME}"
  leaf_update_environment
  leaf_info "Package ${PKG_PREFIX}/${PKG_NAME} has been installed"
}

main $@
